on: [push, pull_request]
    
jobs:
  Publish:
    runs-on: ubuntu-latest
    name: Snap Publish
    steps:
      - name: checkout action
        uses: actions/checkout@v2
        with:
          repository: searchspring/snap-publish
          token: ${{ secrets.ACTION_PAT }}
      - name: Run @searchspring/snap-publish action
        uses: ./
        with:
        # required
          repository: ${{ env.GITHUB_REPOSITORY }}
          secretKey: ${{ secrets.WEBSITE_SECRET_KEY }}
          aws-access-key-id: ${{ secrets.SNAPFU_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SNAPFU_AWS_SECRET_ACCESS_KEY }}
          aws-cloudfront-distribution-id: ${{secrets.SNAPFU_AWS_DISTRIBUTION_ID}}
          aws-s3-bucket-name: ${{secrets.SNAPFU_AWS_BUCKET}}
        # optional
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          skipTests: false
          aws-region: us-east-2
          GITHUB_BOT_TOKEN: ${{ secrets.MACHINE_TOKEN }}